name: nwa12_cobalt

retrospective_forecasts:
  first_year: 1994
  last_year: 2022
  months:
    - 2
    - 6
    - 9
    - 12
  ensemble_size: 5

new_forecasts:
  ensemble_size: 5

snapshots:
  - ocean_month
  - ice_month
  - ocean_cobalt_tracers

climatology:
  first_year: 1993
  last_year: 2022

domain:
  south_lat: 5
  north_lat: 60
  west_lon: -100
  east_lon: -30
  hgrid_file: /home/Andrew.C.Ross/git/nwa12/setup/grid/ocean_hgrid.nc
  ocean_mask_file: /home/Andrew.C.Ross/git/nwa12/setup/grid/ocean_mask.nc
  ocean_static_file: /home/Andrew.C.Ross/git/nwa12/data/geography/ocean_static.nc
  boundaries:
    south: 1
    north: 2
    east: 3

regions:
  mask_file: /home/Andrew.C.Ross/git/nwa12/data/geography/masks/regions_30m.nc 
  names:
    - SS_LME
    - NEUS_LME
    - SEUS_LME
    - GOM
    - MAB
    - GB

variables:
  ocean_month:
    - tos
    - tob
    - sos
    - sob
    - MLD_003
    - ssh
  ocean_daily:
    - tos
    - tob
    - sos
    - ssh
    - MLD_003
  ocean_cobalt_btm:
    - btm_o2
    - btm_co3_sol_arag
    - btm_co3_ion
    - btm_htotal
  ocean_cobalt_omip_sfc:
    - chlos
    - no3os
    - phos
    - po4os
    - sios
    - talkos
  ocean_cobalt_neus:
    - chlos
    - no3os
    - po4os
    - zmesoos
    - nsmp_100
    - nmdp_100
    - nlgp_100
  ocean_neus:
    - MLD_003
    - so
    - thetao
  ocean_cobalt_daily_2d:
    - chlos
    - btm_o2
    - btm_co3_sol_arag
    - btm_co3_ion
    - btm_htotal

filesystem:
  forecast_input_data: /work/acr/mom6/nwa12/forecast_input_data
  nowcast_input_data: /work/acr/mom6/nwa12/analysis_input_data
  forecast_output_data: /work/acr/mom6/nwa12/forecast_output_data
  gaea_input_data: /gpfs/f6/ira-cefi/scratch/Andrew.C.Ross/northwest_atlantic/nwa12_input/forecast_input_data
  yearly_river_files: /work/acr/mom6/nwa12/analysis_input_data/rivers/glofasv4_runoff_{year}.nc
  open_boundary_files: /work/acr/mom6/nwa12/glorys/updated # TODO
  interim_data:
    ERA5: /archive/uda/CEFI/ERA5
    GLORYS_reanalysis: /archive/uda/Global_Ocean_Physics_Reanalysis/global/daily
    GLORYS_analysis: /archive/uda/CEFI/GLOBAL_ANALYSISFORECAST_PHY_001_024/
    GloFAS_ldd: /work/Utheri.Wagura/datasets/glofas/LDD/ldd_glofas_v4_0.nc
    GloFAS_v4: /archive/uda/GloFAS/LISFLOOD/consolidated/global/river_discharge/v4.0/GloFAS_river_discharge_{y}_v4.0.nc
    GloFAS_interim: /uda/CEFI/GloFAS/GloFAS_river_discharge_{y}_v4.0.nc
    # Using version 3 until v4 is fully evaluated
    GloFAS_extension_climatology: /work/acr/mom6/nwa12/forecast_input_common/glofas_runoff_climo_1993_2019_2023-04-v2.nc
  analysis_history: /archive/Andrew.C.Ross/fre/NWA/2024_09/NWA12_COBALT_2024_09_nudgets-90d/gfdl.ncrc6-intel23-prod/history/
  nowcast_history: /archive/Andrew.C.Ross/fre/NWA/2024_09/NWA12_COBALT_2024_09_now_nudgets-90d/gfdl.ncrc6-intel23-prod/3/history/    
  forecast_history: /archive/Andrew.C.Ross/fre/NWA/2024_09/NWA12_cobalt_forecast_2024_09_{year}-{month:02d}-e{ensemble:02d}/gfdl.ncrc6-intel23-prod/history/
  # TODO:need to have process_spear_job.sh read the path to place processed SPEAR data from here
