[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "B", "C4", "UP", "PL", "RUF"]
ignore = ["PLR2004", "PLR0912", "PLR0913"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.isort]
known-first-party = ["analysis_setup"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["E501", "F401", "F403", "F405"]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"
